spring:
  datasource:
    url: jdbc:postgresql://db.reeahmxcmngwqenmogtb.supabase.co:5432/postgres
    username: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true